### ISSUE TITLE
Decoding capabilities detected but hardware decoding is never used

### ISSUE THREAD

**Issue by definitelyuncertain** [saiarcot895/chromium-ubuntu-build#23] opened 2017-12-27 14:19 UTC
I have an 8th Gen i5 with UHD Graphics 620. I'm running Mint 18.3 (based on the Xenial stack) and I've done testing with default drivers. Hardware decode is working via MPV (even 4k@60fps VP9). I'm using the beta PPA.

The `chrome://gpu` page shows this
```
Video Acceleration Information

Decode h264 baseline | up to 4096x4096 pixels
Decode h264 main | up to 4096x4096 pixels
Decode h264 high | up to 4096x4096 pixels
Decode vp8 | up to 4096x4096 pixels
Decode vp9 profile0 | up to 4096x4096 pixels
Decode vp9 profile2 | up to 4096x4096 pixels
Encode h264 baseline | up to 4096x4096 pixels and/or 30.000 fps
Encode h264 main | up to 4096x4096 pixels and/or 30.000 fps
Encode h264 high | up to 4096x4096 pixels and/or 30.000 fps
Encode vp8 | up to 4096x4096 pixels and/or 30.000 fps
```

And there aren't any errors in the terminal. However, all videos I've tried (with and without `h264ify`) use the FFMpeg decoder at any resolution. It seems like HW decode is completely unavailable even though it claims to see all the capabilities. I've checked flags page too.

Although the CPU is very new, UHD 620 is supposed to be a rebranded HD 620, so there's no reason it won't work. Looks like it's back to the drawing board again :(

**Comment by saiarcot895** [comment] 2017-12-27 23:30
I just checked on 64.0.3282.14 (what was on dev and is now on the beta branch), and yes, the GPU isn't being used for video decoding. For a youtube video, the `VpxVideoDecoder` was getting used.

Also, I don't think I've ever seen the video acceleration information you posted in `chrome://gpu` for me, even when it was working. I wonder how it works for you.

**Comment by saiarcot895** [comment] 2017-12-27 23:33
On Chromium startup, there should be some logging messages about the VAAPI libraries being loaded. The fact that there isn't means that something is going wrong early on. (My guess is that some if-else conditional is messed up.)

**Comment by definitelyuncertain** [comment] 2017-12-28 06:23
Ah, that was the problem. Downgrading to 63 fixed it and it works with even VP9.

The VA information isn't present in 63. I heard a while back they were planning to enable it by default in official chromium. Perhaps this is part of some work towards that?

Also, I see you've made a new update. Will that be going in the beta branch?

**Comment by saiarcot895** [comment] 2017-12-29 02:06
Which update? The Beta PPA should have 64.0.3282.39, and the Dev PPA should now have 65.0.3298.3. I tend to update the repository after the builds are successful, so the commits you're seeing now are already in-place.

I did some experimentation, and VAAPI decoding works when Chromium is launched with the `--single-process` argument (This mode also largely breaks how Chromium works, so it's not really usable). `chrome://gpu` shows the decoding information that you posted, and the VAAPI library information is printed on the console. What I've found out so far is that `gl::GetGLImplementation()` (called in `media/gpu/vaapi_wrapper.cc` around line 233) returns Unknown in regular mode, and desktop GL in single process mode. I'm not sure why, maybe due to sandboxing or something? (Although if that were the case, then using the `--no-sandbox` flag should have still worked, but didn't.)

**Comment by saiarcot895** [comment] 2017-12-30 02:03
Whatever the issue is, it got resolved by itself in M65.

**Comment by Mgiv64** [comment] 2018-01-24 10:35
Hello, I'm trying to get the GPUVideoDecode working on an Intel HD Graphics 620 on Ubuntu 17.10 with  Chromium 64 from your PPA but the video decode doesn't seems to work (no VA-API message in the console on Chromium startup, only ffmpegVideoDecode in chrome://media-internals). 

I understand in your comments on this post I should use the 63 version or the latest 65. Does these version available on your PPA or should I compile from your sources myself ?

Is there a docs/website somewhere that list everything which is needed to make GPUVideoDecode working. From your point of view should it be possible with this Intel HD Graphics and this version of Ubuntu ? Thanks you very much for you help.

**Comment by saiarcot895** [comment] 2018-01-24 16:21
@Mgiv64 Which PPA are you using? The Beta PPA is on 64, the Dev PPA is on 65.

**Comment by Mgiv64** [comment] 2018-01-24 20:17
Hi @saiarcot895, I've tried both and I have the same result. I've also get a message on start that this version of chromium requires va-api 0.39 and my system has the 0.40. I've downgraded to 0.39 then retried, I had no error message anymore but no hardware decode yet. Do you have any advice ? Thanks

**Comment by progredior** [comment] 2018-02-25 12:12
I tried 17.10 and 18.04 clean installs without YoutTube acceleration success, mpv acceleration works fine.
Version 65.0.3325.73 (Developer Build) Ubuntu 18.04 (64-bit)
Intel® HD Graphics 620 (Kaby Lake GT2)
Video Decode: Hardware accelerated
video_decoder | VpxVideoDecoder

**Comment by Mgiv64** [comment] 2018-02-25 19:35
Thanks @progredior. I will try one more time with this version.
I'm running Xubuntu instead of Ubuntu, maybe this is the source of my problem. 
What do you think?

**Comment by progredior** [comment] 2018-02-25 21:44
It didn't work for me, even with --single-process flag, Ubuntu 17.10 or 18.04 no success, only acceleration in mpv worked.

**Comment by Mgiv64** [comment] 2018-02-26 12:51
Hi, great news it worked for me with the current dev version (65).
GpuVideoDecode appears in chrome://media-internals instead of FFmpegVideoDecode.
@progredio, try to "apt install" and run "vainfo" to check is the va-api is correctly installed on your system.
Now I'm facing the "Google API Key is missing" error that shows. (I was able to hide this in previous versions with --disable-infobars but it's not working anymore)

**Comment by saiarcot895** [comment] 2018-02-26 20:59
Based on this thread, GPU video decoding seems to be a bit finicky, working on one version and not working on another. I haven't made any  major changes to the patch, except the changes necessary to make it compile.

I'm trying to get dev version 66 and beta version 65 built; hopefully I'll have that done today/early tomorrow, and then we can test it out and see if it's working.

**Comment by definitelyuncertain** [comment] 2018-02-27 07:17
> GPU video decoding seems to be a bit finicky

Works for me in 65 (from dev, not beta) except when I upgraded to Nvidia driver version 390.

Also,

> If you're currently on 65, then that is the beta version, not dev. Dev is on 66.

I can't get 65 in beta at all, only 64. Did it get disabled because of a build failure? Similar situation with 66 in dev.

**Comment by saiarcot895** [comment] 2018-02-27 07:18
66 in dev is having build issues (hopefully sorted out). 65 in beta is available for 17.10 and 18.04 (16.04 is having build issues).

**Comment by saiarcot895** [comment] 2018-03-01 16:42
Dev has been updated to 66 for 16.04 and newer, and Beta has been updated to 65 for 16.04 and newer. Please test with these versions.

**Comment by definitelyuncertain** [comment] 2018-03-01 19:11
VA works for me in both 65 beta and 66 dev on Nvidia driver 384. Thanks!

**Closed** 2018-05-27 16:17 UTC
