### ISSUE TITLE
Problems with beta-ppa on 21.10 (impish)

### ISSUE THREAD

**Issue by GatoLoko** [saiarcot895/chromium-ubuntu-build#118] opened 2021-09-16 17:22 UTC
The packages aren't available on the impish repository, so I'm using the repo for hirsute to install.

The browser doesn't completely crash, but it's useless. Nothing works. The "new tab" fails to load, writing an URL fails just the same, any installed extensions crashes on launch and can't be reloaded, the extension manager can't be used to disable them, removing the user profile to start clean fails just the same.

I've tried uninstalling all chromium packages (sudo apt purge chromium-browser chromium-browser-l10n chromium-codecs-ffmpeg-extra), changing the repository to focal (20.04), it required manually downloading libpipewire-0.2-1 from ubuntu repositories and installing it with dpkg, the packages installed properly but it fails just the same.

It seems that nothing works on 21.10.

I'll add a screenshot after this, but there isn't much to be seen.

**Comment by GatoLoko** [comment] 2021-09-16 17:23
![Chromium-Ubuntu-21 10](https://user-images.githubusercontent.com/3594370/133657232-15320546-0cf7-4e5a-9577-d66fade0ee0c.png)

**Comment by GatoLoko** [comment] 2021-09-16 17:36
Launching it on the terminal with different parameters to check for differences:

$ chromium-browser                                                                     
[100517:100517:0916/192755.807895:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!

$ chromium-browser --use-gl=desktop                                                    
[107918:107918:0916/192955.819486:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is desktop
[107918:107918:0916/192955.898810:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!

$ chromium-browser --disable-gpu --disable-software-rasterizer                     1  
[113374:113374:0916/193430.398468:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled
[113322:113360:0916/193430.443048:ERROR:gpu_process_host.cc(1002)] GPU process exited unexpectedly: exit_code=31
[113397:113397:0916/193431.166966:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled
[113397:113397:0916/193431.169399:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.

I don't know what else to try.

**Comment by saiarcot895** [comment] 2021-09-22 04:35
Duplicate of #114.

**Closed by saiarcot895** 2021-09-22 04:35 UTC
