### ISSUE TITLE
Hardware acceleration no longer works after latest Dev PPA update in Ubuntu Cosmic (72.0.3610.2-0ubuntu1~ppa4~18.10.1)

### ISSUE THREAD

**Issue by logix2** [saiarcot895/chromium-ubuntu-build#37] opened 2018-11-22 19:42 UTC
After the latest Chromium update from the Dev PPA in Ubuntu 18.10, hardware acceleration no longer works. It was working previously.

```
$ apt-cache policy chromium-browser
chromium-browser:
  Installed: 72.0.3610.2-0ubuntu1~ppa4~18.10.1
  Candidate: 72.0.3610.2-0ubuntu1~ppa4~18.10.1
  Version table:
 *** 72.0.3610.2-0ubuntu1~ppa4~18.10.1 500
        500 http://ppa.launchpad.net/saiarcot895/chromium-dev/ubuntu cosmic/main amd64 Packages
        100 /var/lib/dpkg/status
     70.0.3538.77-0ubuntu0.18.10.1 500
        500 http://security.ubuntu.com/ubuntu cosmic-security/universe amd64 Packages
        500 http://archive.ubuntu.com/ubuntu cosmic-updates/universe amd64 Packages
     69.0.3497.100-0ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu cosmic/universe amd64 Packages
```

I'm using Chromium in Ubuntu 18.10 with the ``vdpau-va-driver`` package from Ubuntu 18.04 from the PPA (this package was not updated in your PPA for Ubuntu 18.10 so I've marked it to not be updated from Ubuntu):
```
$ apt-cache policy vdpau-va-driver
vdpau-va-driver:
  Installed: 0.7.4-6ubuntu2~ppa1~18.04.1
  Candidate: 0.7.4-7
  Version table:
     0.7.4-7 500
        500 http://archive.ubuntu.com/ubuntu cosmic/universe amd64 Packages
 *** 0.7.4-6ubuntu2~ppa1~18.04.1 100
        100 /var/lib/dpkg/status
```

I get this error multiple times when running Chromium:
```
vdpau_video: vaTerminate(): config ID 0x01000000 is still allocated, destroying
```
Let me know if you need any other info.

**Comment by Esokrates** [comment] 2018-11-23 08:51
I can confirm this. Happens to me too on intel without vdpau. I did not see any vaapi related error on command line.
Rolled back to the previous build in the meantime.

**Comment by sreerenjb** [comment] 2018-11-23 19:15
I too can reproduce this issue with intel vaapi driver. Issue is there for both VA-1.2 and VA-1.3 compatible drivers. I think this is an issue with 72.0.3610.2-0ubuntu1~ppa3~18.10.1 (even tired manual build from the source) update since it was working fine with 72.0.3590.0-0ubuntu1~ppa1~18.10.1.

How can I get a tarball of 72.0.3590.0-0ubuntu1~ppa1~18.10.1? Just wanna try a manual compilation for this.

**Comment by saiarcot895** [comment] 2018-11-23 21:04
I'll take a look when I get a chance.

Using apt source should work. Alternatively, you can go to the PPA page, click on view package details, and grab the dsc file for the package and use dget. 

On November 23, 2018 11:15:33 AM PST, Sreerenj Balachandran <notifications@github.com> wrote:
>I too can reproduce this issue with intel vaapi driver. Issue is there
>for both VA-1.2 and VA-1.3 compatible drivers. I think this is an issue
>with 72.0.3610.2-0ubuntu1~ppa3~18.10.1 (even tired manual build from
>the source) update since it was working fine with
>72.0.3590.0-0ubuntu1~ppa1~18.10.1.
>
>How can I get a tarball of 72.0.3590.0-0ubuntu1~ppa1~18.10.1? Just
>wanna try a manual compilation for this.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/saiarcot895/chromium-ubuntu-build/issues/37#issuecomment-441305921

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sreerenjb** [comment] 2018-11-24 03:33
Never mind, I tried the 71.0.3578.20 from beta branch and that is working fine with vaapi. At least it is showing gpuvideodecoder in media-internals.

**Comment by Esokrates** [comment] 2018-11-24 09:37
@sreerenjb You can find everything in here: http://ppa.launchpad.net/saiarcot895/chromium-dev/ubuntu/pool/main/c/chromium-browser/

**Comment by saiarcot895** [comment] 2018-12-03 01:37
I've done some experimentation (aka guess-and-check), and I suspect that [this](https://chromium-review.googlesource.com/q/I40ea00150f7dadfe2319e2cdb27e3be5f29a702c) change is causing the breakage here. [This](https://chromium-review.googlesource.com/q/I0279d839a83ff67ac37508aad8de632b237fa65e) commit reverted it for ChromeOS. See [this](https://chromium.googlesource.com/chromium/src.git/+/master/media/renderers/default_decoder_factory.cc#106) comment stating that enabling the MojoVideoDecoder replaces any VDA (video decode accelerator).

I'll look into disabling this for my PPA, and hopefully have a build in a couple of days..

**Comment by saiarcot895** [comment] 2018-12-03 01:53
I'll later need to look into seeing if using the GPU with MojoVideoDecoder can be done easily.

**Comment by saiarcot895** [comment] 2018-12-03 15:29
The fixed build isn't up yet.

**Comment by omen23** [comment] 2018-12-03 18:07
will you roll back to GpuVideoDecoder or use MojoVideoDecoder?
Cool that you fixed it: thumbs up - its so unfair that google doesnt
provide chrome/chromium with HW accel and widevine on linux.
Thanks for your work! (=


Am Mo., 3. Dez. 2018 um 16:30 Uhr schrieb Saikrishna Arcot <
notifications@github.com>:

**Comment by saiarcot895** [comment] 2018-12-03 18:22
I'll revert it to use GpuVideoDecoder. Later, once ChromeOS starts using MojoVideoDecoder, I'll look at transitioning over to that.

**Comment by sumartoyo** [comment] 2018-12-05 04:52
72.0.3622.0-0ubuntu1~ppa4 GPU video decoding works on 16.04. 72.0.3610.2 was also doesn't work on 16.04. Widevine still doesn't work though.

**Comment by omen23** [comment] 2018-12-05 09:50
GPU accel works on nvidia platforms again (K)ubuntu 18.10 confirmed

Am Mi., 5. Dez. 2018 um 05:52 Uhr schrieb Dimas <notifications@github.com>:

**Comment by Esokrates** [comment] 2018-12-05 12:48
Confirming the fix in 18.10 using Intel Graphics.

**Comment by saiarcot895** [comment] 2018-12-05 15:52
@sumartoyo Widevine still being broken is a known issue.

Closing this issue.

**Closed by saiarcot895** 2018-12-05 15:52 UTC

**Comment by omen23** [comment] 2019-01-10 16:26
VAAPI acceleration with NVIDIA GPUs doesnt work anymore with build 73.0.3664.3

```
Log Messages
[7914:7914:0110/172241.365928:WARNING:gpu_video_decode_accelerator.cc(383)] : Created the VDA factory
[7914:7914:0110/172241.365963:WARNING:gpu_video_decode_accelerator_factory.cc(246)] : Initializing VAAPI VDA.
[7914:7914:0110/172241.395425:WARNING:gpu_video_decode_accelerator.cc(397)] : Created VDA
[7914:7914:0110/172241.400165:ERROR:vaapi_wrapper.cc(1470)] : vaCreateConfig failed VA error: the requested VAProfile is not supported
[7914:7914:0110/172241.400217:ERROR:vaapi_wrapper.cc(851)] : Failed to create VaapiWrapper for va_profile: -1
[7914:7914:0110/172251.028977:WARNING:gpu_video_decode_accelerator.cc(383)] : Created the VDA factory
[7914:7914:0110/172251.029004:WARNING:gpu_video_decode_accelerator_factory.cc(246)] : Initializing VAAPI VDA.
[7914:7914:0110/172251.068072:WARNING:gpu_video_decode_accelerator.cc(397)] : Created VDA
[7914:7914:0110/172251.071247:ERROR:vaapi_wrapper.cc(1470)] : vaCreateConfig failed VA error: the requested VAProfile is not supported
[7914:7914:0110/172251.071299:ERROR:vaapi_wrapper.cc(851)] : Failed to create VaapiWrapper for va_profile: -1
[7914:7914:0110/172330.713441:WARNING:x11_util.cc(1425)] : X error received: serial 486, error_code 3 (BadWindow), request_code 4, minor_code 0 (Unknown)
[7914:8106:0110/172330.776564:WARNING:x11_util.cc(1425)] : X error received: serial 3628, error_code 3 (BadWindow), request_code 4, minor_code 0 (Unknown)
```
