### ISSUE TITLE
1:100.0.4878.0-0ubuntu1~ppa4~20.04.1 terminates automatically

### ISSUE THREAD

**Issue by econo202** [saiarcot895/chromium-ubuntu-build#122] opened 2022-03-25 19:58 UTC
I've just installed Chromium `1:100.0.4878.0-0ubuntu1~ppa4~20.04.1 ` from `ppa:saiarcot895/chromium-dev` and whenever I want to run it, the browser terminates automatically throwing some errors:

> [94642:94642:0325/205240.802286:ERROR:sandbox_linux.cc(377)] InitializeSandbox()
>  called with multiple threads in process gpu-process.                           
> [94604:94604:0325/205241.346189:ERROR:system_web_app_manager.cc(320)] Exceeded S
> WA install retry attempts.  Skipping installation, will retry on next OS update 
> or when locale changes.
> *** stack smashing detected ***: terminated
> Received signal 6
> #0 0x55a52b2a69e9 (/usr/lib/chromium-browser/chromium-browser+0x525c9e8)
> #1 0x55a52b20b6d3 (/usr/lib/chromium-browser/chromium-browser+0x51c16d2)
> #2 0x55a52b2a64d1 (/usr/lib/chromium-browser/chromium-browser+0x525c4d0)
> #3 0x7f9b589023c0 (/usr/lib/x86_64-linux-gnu/libpthread-2.31.so+0x143bf)
> #4 0x7f9b576eb03b gsignal
> #5 0x7f9b576ca859 abort
> #6 0x7f9b5773529e (/usr/lib/x86_64-linux-gnu/libc-2.31.so+0x8d29d)
> #7 0x7f9b577d7aea __fortify_fail
> #8 0x7f9b577d7ab6 __stack_chk_fail

(...)

I've tried `--disable-gpu` and `--disable-software-rasterizer`, but no luck.

**Comment by saiarcot895** [comment] 2022-03-26 16:07
You might be hitting [this](https://bugs.chromium.org/p/chromium/issues/detail?id=1304756) issue. The issue was caused by a bug in the component updater code, and during browser startup, the PKI metadata gets downloaded and is running into the bug. This was fixed in a later dev version, which should now be available for 20.04.

I don't know why the original bug report is now behind a login (and possibly restricted to certain people).

**Comment by econo202** [comment] 2022-03-27 18:57
Thank you for pointing the relevant Chromium issue.

The problem is gone after updating to version 101.

**Closed** 2022-03-27 18:58 UTC
