### ISSUE TITLE
Content Display Issues 

### ISSUE THREAD

**Issue by robotard** [saiarcot895/chromium-ubuntu-build#117] opened 2021-08-17 16:27 UTC
Chromium 93.0.4573.0 (Developer Build) Ubuntu 21.04 (64-bit)

The latest Dev and Beta builds both appear to have issues on my Ubuntu with regards to displaying most content... Most visible are chrome://gpu showing an unpopulated list ( chart) chrome://flags not displaying Dropdown options, but most web content is not displayed at all.

Have attached screenshots, and attempted to reinstall both Beta and Dev after apt purge.  

Please let me know how to best test relevant fixes or whether to your knowledge, the latest Chromium supports Hardware Acceleration. I am using Chromium mainly for Stadia, and use Chrome as my daily driver.

![Ubuntu21_04Settings](https://user-images.githubusercontent.com/4448625/129763816-09f15f04-0a9a-41d9-ad42-e92f176530e0.png)
![ChromiumFlags](https://user-images.githubusercontent.com/4448625/129762476-bbc83786-5528-437f-b1e0-dd24147bd21f.png)
![ChromiumGPUFlag](https://user-images.githubusercontent.com/4448625/129762484-0d870d56-5cbd-4e39-8dcb-088be16b3503.png)
![ChromiumVersion](https://user-images.githubusercontent.com/4448625/129762488-6c48028c-bd58-4a3c-9d17-03e991ad4423.png)

**Comment by saiarcot895** [comment] 2021-09-22 04:35
Duplicate of #114.

**Closed by saiarcot895** 2021-09-22 04:35 UTC
