### ISSUE TITLE
libva error

### ISSUE THREAD

**Issue by helijia21** [saiarcot895/chromium-ubuntu-build#47] opened 2019-04-17 05:50 UTC
- $ `chromium-browser` 
  - `libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed`
  - `[9641:9641:0417/133844.276963:ERROR:vaapi_wrapper.cc(343)] vaInitialize failed (ignore if using Wayland desktop environment): unknown libva error`
  - `[9641:9641:0417/133844.328009:ERROR:sandbox_linux.cc(368)] InitializeSandbox() called with multiple threads in process gpu-process.`
  - `[9641:9641:0417/133844.716426:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command `

- version Chromium 75.0.3759.4 Ubuntu 18.10(dev)
- $ `vainfo`
  - `libva info: VA-API version 1.2.0`
  - `libva info: va_getDriverName() returns 0`
  - `libva info: User requested driver 'i965'`
  - `libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so`
  - `libva info: Found init function __vaDriverInit_1_2`
  - `libva info: va_openDriver() returns 0`
  - `vainfo: VA-API version: 1.2 (libva 2.2.0)`
  - `vainfo: Driver version: Intel i965 driver for Intel(R) Broadwell - 2.2.0`

- ubuntu 18.10 with wayland 
- intel gpu

Can not apply the gpu accelerate, find the `video_decode` is `FFmpegVideoDecoder`

**Comment by saiarcot895** [comment] 2019-04-17 15:40
This is a known issue. Hardware acceleration doesn't work on wayland. Duplicate of #20.

**Closed** 2019-04-17 15:41 UTC
