### ISSUE TITLE
clang++: error: unknown argument: '-ftrivial-auto-var-init=pattern'

### ISSUE THREAD

**Issue by timrichardson** [saiarcot895/chromium-ubuntu-build#69] opened 2019-12-27 09:58 UTC
I grabbed the debian directory of the latest beta release (matching this source: file:///home/tim/development/chromium-source/chromium-browser_80.0.3987.16.orig.tar.xz)
The patches all apply; I used the bionic series. But as soon as it starts compiling (that is, after the build tools compile finishes), this happens on every executable:
clang++: error: unknown argument: '-ftrivial-auto-var-init=pattern'
I know I can work around this by forcing it to use clang-8 but I don't understand how the autobuild succeeds; does clang default to some other version?

**Comment by saiarcot895** [comment] 2019-12-27 17:11
Bionic uses Clang 6.0. Make sure that you're applying the patches listed in `debian/patches/series` file.

If you want to, you can set up either pbuilder or sbuild (pbuilder is easier to set up), pass in the dsc file (you can get that for each package version from [this](https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-beta/+packages) page), and have pbuilder/sbuild build the package.

For what it's worth though, in the dev PPA, Chromium has been compiled for Bionic and higher, whereas in the beta PPA, Chromium has been compiled for Disco and higher. Bionic compile for beta and Xenial compile for both beta and dev will be fixed once I copy/fix over some patches. There's also some issues with the build daemon on Launchpad, so it might take a while.

**Comment by timrichardson** [comment] 2019-12-27 22:12
Thanks. My attempt was based on your beta archive. Also, I used the bionic patch series, is this not correct?

It compiles when I change debian/rules to refer to clang 8 (copying the main repository version) and change the version to clang8 in the patch `use-clang-versioned-bionic.patch`

If you try to use clang6, how is `"unknown argument: '-ftrivial-auto-var-init=pattern'"` avoided?
The learning curve for all of this is quite steep, and I can't see how this problem is solved if building with clang6.

**Comment by saiarcot895** [comment] 2019-12-27 23:55
Interesting, I can confirm that Clang 6 is the only version of Clang's that installed.

The bionic patch series is definitely the one that should be used.

In the full build command that gets printed out for the error, does it have `-Wno-unknown-warning-option` as one of its options?

**Comment by timrichardson** [comment] 2019-12-28 20:14
The warning patch is definitely working, I build it without it once a couple of days ago, and there were warnings after each build. That was a build where I forced clang 8, and it worked. 
No such warning appears when I include the patch. But the problem is not a warning, it is a clang fatal error. The source doesn't compile with clang6. 

1. I downloaded latest  chromium-browser_80.0.3987.16-0ubuntu1_ppa2_18.04.1.debian.tar.xz from your beta ppa
2. got the original, applied the bionic.series via quilt push -a
3. debian/rules build

The first 182 complies work (setting up gn)
And then it stops: ...
Every compile looks like this (first five shown):

```
 ^----
The variable "strip_absolute_paths_from_debug_symbols" was set as a build argument
but never appeared in a declare_args() block in any buildfile.

To view all possible args, run "gn args --list <out_dir>"

The build continued as if that argument was unspecified.

Done. Made 11198 targets from 2048 files in 3451ms
make[1]: Leaving directory '/home/tim/development/chromium-source'
   debian/rules override_dh_auto_build
make[1]: Entering directory '/home/tim/development/chromium-source'
debian/rules:164: Google API info is not set in build variables GOOGLEAPI_APIKEY_ GOOGLEAPI_CLIENTID_ GOOGLEAPI_CLIENTSECRET_
ninja -k 3 -C /home/tim/development/chromium-source/out/final pdf chrome chromedriver clear_key_cdm 
ninja: Entering directory `/home/tim/development/chromium-source/out/final'
[1/39522] CXX obj/buildtools/third_party/libc++/libc++/shared_mutex.o
FAILED: obj/buildtools/third_party/libc++/libc++/shared_mutex.o 
/usr/bin/clang++ -MMD -MF obj/buildtools/third_party/libc++/libc++/shared_mutex.o.d -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_OVERRIDABLE_FUNC_VIS=__attribute__\(\(__visibility__\(\"default\"\)\)\) -DLIBCXX_BUILDING_LIBCXXABI -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -DCR_LIBCXX_REVISION=375504 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g1 -ftrivial-auto-var-init=pattern -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -fstrict-aliasing -fPIC -Wall -Wno-unused-variable -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-unknown-warning-option -Wno-undefined-var-template -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-bitwise-conditional-parentheses -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -std=c++14 -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include -fvisibility-inlines-hidden -fexceptions -frtti -c ../../buildtools/third_party/libc++/trunk/src/shared_mutex.cpp -o obj/buildtools/third_party/libc++/libc++/shared_mutex.o
clang++: error: unknown argument: '-ftrivial-auto-var-init=pattern'
[2/39522] CXX obj/buildtools/third_party/libc++/libc++/string.o
FAILED: obj/buildtools/third_party/libc++/libc++/string.o 
/usr/bin/clang++ -MMD -MF obj/buildtools/third_party/libc++/libc++/string.o.d -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_OVERRIDABLE_FUNC_VIS=__attribute__\(\(__visibility__\(\"default\"\)\)\) -DLIBCXX_BUILDING_LIBCXXABI -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -DCR_LIBCXX_REVISION=375504 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g1 -ftrivial-auto-var-init=pattern -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -fstrict-aliasing -fPIC -Wall -Wno-unused-variable -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-unknown-warning-option -Wno-undefined-var-template -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-bitwise-conditional-parentheses -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -std=c++14 -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include -fvisibility-inlines-hidden -fexceptions -frtti -c ../../buildtools/third_party/libc++/trunk/src/string.cpp -o obj/buildtools/third_party/libc++/libc++/string.o
clang++: error: unknown argument: '-ftrivial-auto-var-init=pattern'
[3/39522] CXX obj/buildtools/third_party/libc++/libc++/system_error.o
FAILED: obj/buildtools/third_party/libc++/libc++/system_error.o 
/usr/bin/clang++ -MMD -MF obj/buildtools/third_party/libc++/libc++/system_error.o.d -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_OVERRIDABLE_FUNC_VIS=__attribute__\(\(__visibility__\(\"default\"\)\)\) -DLIBCXX_BUILDING_LIBCXXABI -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -DCR_LIBCXX_REVISION=375504 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g1 -ftrivial-auto-var-init=pattern -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -fstrict-aliasing -fPIC -Wall -Wno-unused-variable -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-unknown-warning-option -Wno-undefined-var-template -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-bitwise-conditional-parentheses -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -std=c++14 -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include -fvisibility-inlines-hidden -fexceptions -frtti -c ../../buildtools/third_party/libc++/trunk/src/system_error.cpp -o obj/buildtools/third_party/libc++/libc++/system_error.o
clang++: error: unknown argument: '-ftrivial-auto-var-init=pattern'
[4/39522] CXX obj/buildtools/third_party/libc++/libc++/stdexcept.o
FAILED: obj/buildtools/third_party/libc++/libc++/stdexcept.o 
/usr/bin/clang++ -MMD -MF obj/buildtools/third_party/libc++/libc++/stdexcept.o.d -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_OVERRIDABLE_FUNC_VIS=__attribute__\(\(__visibility__\(\"default\"\)\)\) -DLIBCXX_BUILDING_LIBCXXABI -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -DCR_LIBCXX_REVISION=375504 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g1 -ftrivial-auto-var-init=pattern -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -fstrict-aliasing -fPIC -Wall -Wno-unused-variable -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-unknown-warning-option -Wno-undefined-var-template -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-bitwise-conditional-parentheses -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -std=c++14 -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include -fvisibility-inlines-hidden -fexceptions -frtti -c ../../buildtools/third_party/libc++/trunk/src/stdexcept.cpp -o obj/buildtools/third_party/libc++/libc++/stdexcept.o
clang++: error: unknown argument: '-ftrivial-auto-var-init=pattern'
```

After the 12th one:

```
[12/39522] CXX obj/buildtools/third_party/libc++/libc++/strstream.o
FAILED: obj/buildtools/third_party/libc++/libc++/strstream.o 
/usr/bin/clang++ -MMD -MF obj/buildtools/third_party/libc++/libc++/strstream.o.d -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_OVERRIDABLE_FUNC_VIS=__attribute__\(\(__visibility__\(\"default\"\)\)\) -DLIBCXX_BUILDING_LIBCXXABI -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -DCR_LIBCXX_REVISION=375504 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -O2 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g1 -ftrivial-auto-var-init=pattern -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -fstrict-aliasing -fPIC -Wall -Wno-unused-variable -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-unknown-warning-option -Wno-undefined-var-template -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-bitwise-conditional-parentheses -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -std=c++14 -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include -fvisibility-inlines-hidden -fexceptions -frtti -c ../../buildtools/third_party/libc++/trunk/src/strstream.cpp -o obj/buildtools/third_party/libc++/libc++/strstream.o
clang++: error: unknown argument: '-ftrivial-auto-var-init=pattern'
ninja: build stopped: subcommands failed.
debian/rules:226: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 1
make[1]: Leaving directory '/home/tim/development/chromium-source'
debian/rules:191: recipe for target 'build' failed
make: *** [build] Error 2

```

I can get to it work by copying 'upstream' if that that's the term, and specifying clang8 in two places: in debian/rules, and in the versioned clang patch. 

Is a patch supposed to turn off the unknown argument "'-ftrivial-auto-var-init=pattern' ?

**Comment by timrichardson** [comment] 2019-12-28 20:17
PS:
tim@moncrief:~/development/chromium-source$ clang --version
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
tim@moncrief:~/development/chromium-source$ which clang
/usr/bin/clang
tim@moncrief:~/development/chromium-source$

**Comment by saiarcot895** [comment] 2019-12-28 21:19
In `debian/rules`, at around lines 175-180, if you're building on Ubuntu 16.04 or 18.04, then `init_stack_vars=false` is specified, which will then cause that flag to not get added. (The conditional is specified in a bit of a complicated way). If you're building on any other version of Ubuntu, then `init_stack_vars=true` is specified.

**Comment by timrichardson** [comment] 2019-12-28 22:22
Ok so perhaps me using KDE Neon is the problem

**Comment by timrichardson** [comment] 2019-12-28 22:30
Can rules set a variable for the clang version it is going to use?

**Comment by timrichardson** [comment] 2019-12-28 22:38
I get DEBIAN_DIST_VERSION = 18.04 but DEBIAN_DIST is 'KDE neon User Edition 5.17'

**Comment by saiarcot895** [comment] 2019-12-29 01:05
You'd need to fix up lines 29-36 of that file. Note that the variable later on being checked is `UBUNTU_DIST`, and that variable gets set only if `Ubuntu` is in `DEBIAN_DIST`. It looks like `DEBIAN_DIST_VERSION` is only used for generating the startup shell script.

**Comment by timrichardson** [comment] 2019-12-29 06:05
This fixes it

tim@moncrief:~/development/chromium-ubuntu-build$ (git_issue_69)git diff master debian/rules
```
diff --git a/debian/rules b/debian/rules
index edafe50..3262348 100755
--- a/debian/rules
+++ b/debian/rules
@@ -31,6 +31,11 @@ DISTRIBUTION=UBUNTU
 UBUNTU_DIST=$(DEBIAN_DIST)
 endif
 
+ifneq (,$(findstring neon,$(DEBIAN_DIST)))
+DISTRIBUTION=UBUNTU
+UBUNTU_DIST=$(DEBIAN_DIST_VERSION)
+endif
+
 ifneq (,$(findstring Debian,$(DEBIAN_DIST)))
 DISTRIBUTION=DEBIAN
 endif
```

**Comment by timrichardson** [comment] 2020-02-26 22:10
Failing differently now:
The variable "strip_absolute_paths_from_debug_symbols" was set as a build argument
but never appeared in a declare_args() block in any buildfile.

To view all possible args, run "gn args --list <out_dir>"

The build continued as if that argument was unspecified.

Done. Made 11809 targets from 2123 files in 5056ms
make[1]: Leaving directory '/home/tim/development/chromium-ubuntu-build'
   debian/rules override_dh_auto_build
make[1]: Entering directory '/home/tim/development/chromium-ubuntu-build'
debian/rules:171: Google API info is not set in build variables GOOGLEAPI_APIKEY_UBUNTU GOOGLEAPI_CLIENTID_UBUNTU GOOGLEAPI_CLIENTSECRET_UBUNTU
ninja -k 3 -C /home/tim/development/chromium-ubuntu-build/out/final pdf chrome chromedriver clear_key_cdm 
ninja: Entering directory `/home/tim/development/chromium-ubuntu-build/out/final'
[1/40498] CXX obj/base/base_static/base_switches.o
[2/40498] AR obj/base/libbase_static.a
FAILED: obj/base/libbase_static.a 
rm -f obj/base/libbase_static.a && "../../../../../../usr/bin/llvm-ar" -T -r -c -s -D obj/base/libbase_static.a @"obj/base/libbase_static.a.rsp"
llvm-ar: Unknown command line argument '-r'.  Try: '../../../../../../usr/bin/llvm-ar -help'
llvm-ar: Did you mean '-M'?
llvm-ar: Unknown command line argument '-c'.  Try: '../../../../../../usr/bin/llvm-ar -help'
llvm-ar: Did you mean '-M'?
llvm-ar: Unknown command line argument '-s'.  Try: '../../../../../../usr/bin/llvm-ar -help'
llvm-ar: Did you mean '-M'?
llvm-ar: Unknown command line argument '-D'.  Try: '../../../../../../usr/bin/llvm-ar -help'
llvm-ar: Did you mean '-M'?

**Comment by saiarcot895** [comment] 2020-04-10 16:34
Closing as this issue got fixed

**Closed by saiarcot895** 2020-04-10 16:34 UTC
