### ISSUE TITLE
DEBUG GetConfigAttributes fails for H264 profiles but VAAPI acceleration is working in 77.0.3833.0-0ubuntu1~ppa2~19.04.1

### ISSUE THREAD

**Issue by omen23** [saiarcot895/chromium-ubuntu-build#52] opened 2019-06-27 03:18 UTC
Log entries from `about:gpu` : 
```
Log Messages
[14293:14293:0627/051216.685360:ERROR:vaapi_wrapper.cc(516)] : GetConfigAttributes failed for va_profile VAProfileH264Baseline
[14293:14293:0627/051216.685449:ERROR:vaapi_wrapper.cc(516)] : GetConfigAttributes failed for va_profile VAProfileH264Main
[14293:14293:0627/051216.685459:ERROR:vaapi_wrapper.cc(516)] : GetConfigAttributes failed for va_profile VAProfileH264High
[14293:14293:0627/051227.491565:WARNING:gpu_video_decode_accelerator_factory.cc(234)] : Initializing VAAPI VDA.
```
Using GTX 1070 with 430.26 but `nvidia-settings` shows `Video Engine Utilization` and so does `nvidia-smi` – so it is just an cosmetic/optical bug. Idk if it really changes libVAs behaviour.
regards

**Comment by JurgenWolf** [comment] 2019-07-25 20:20
Not just cosmetic.
Since this BUG appeared - I see lags at 1080p, only 720p works smoothly.

**Comment by omen23** [comment] 2019-07-26 10:57
I get no performance penalty, same Video Engine Utilization and the same
nvidia-smi output regarding memory usage at the same amount of video
playing tabs.

Regards

Am Do., 25. Juli 2019 um 22:20 Uhr schrieb JurgenWolf <
notifications@github.com>:

**Comment by JurgenWolf** [comment] 2019-07-26 12:33
`--disable-features=MojoVideoDecoder` doesn't work anymore since v76 or so...
Previously I have used legacy GPU videodecoder - were no lags at 1080p youtube on my machine.

So if it is not related to those errors for profiles - then it is related to Mojo.

**Comment by JurgenWolf** [comment] 2019-07-27 02:37
I think, this thread should be merged with https://github.com/saiarcot895/chromium-ubuntu-build/issues/46

**Comment by omen23** [comment] 2019-07-28 16:36
```
[11310:11310:0728/183217.396878:ERROR:vaapi_wrapper.cc(512)] GetConfigAttributes failed for va_profile VAProfileH264Baseline
[11310:11310:0728/183217.396943:ERROR:vaapi_wrapper.cc(512)] GetConfigAttributes failed for va_profile VAProfileH264Main
[11310:11310:0728/183217.396950:ERROR:vaapi_wrapper.cc(512)] GetConfigAttributes failed for va_profile VAProfileH264High
```
in 77.0.3860.5-0ubuntu1~ppa1~19.04.1 – on my GTX 1070 this is still a optical problem — h264 gets decoded via the graphics card.
```
render_id: 39
player_id: 32
origin_url: https://www.youtube.com/
frame_url: https://www.youtube.com/watch?v=lyG942-zMmg
frame_title: (4) PewDiePie - YouTube
surface_layer_mode: kAlways
url: blob:https://www.youtube.com/2f0eb0c2-4ce2-4b7d-a57b-e8a2021cd390
info: Selected video track: []
pipeline_state: kPlaying
found_audio_stream: true
audio_codec_name: aac
found_video_stream: true
video_codec_name: h264
event: PLAY
audio_dds: false
audio_decoder: FFmpegAudioDecoder
is_platform_audio_decoder: false
video_dds: false
video_decoder: MojoVideoDecoder
is_platform_video_decoder: true
audio_buffering_state: BUFFERING_HAVE_ENOUGH
height: 720
width: 1280
video_buffering_state: BUFFERING_HAVE_ENOUGH
for_suspended_start: false
pipeline_buffering_state: BUFFERING_HAVE_ENOUGH
duration: 1352.260498
```

**Comment by JurgenWolf** [comment] 2019-07-28 16:45
I switched back to v74 build - where no issues with profiles and no lags/freezing.
It works as expected.

**Comment by omen23** [comment] 2019-07-29 06:32
```
render_id: 88
player_id: 28
origin_url: https://www.youtube.com/
frame_url: https://www.youtube.com/watch?v=y5Pgre11bFg
frame_title: (5) PewDiePie - YouTube
surface_layer_mode: kAlways
url: blob:https://www.youtube.com/136e5127-eb89-4279-97a3-aea453723302
info: Selected video track: []
pipeline_state: kPlaying
found_audio_stream: true
audio_codec_name: aac
found_video_stream: true
video_codec_name: h264
event: PLAY
audio_dds: false
audio_decoder: FFmpegAudioDecoder
is_platform_audio_decoder: false
video_dds: false
video_decoder: MojoVideoDecoder
is_platform_video_decoder: true
audio_buffering_state: BUFFERING_HAVE_ENOUGH
height: 1080
width: 1920
video_buffering_state: BUFFERING_HAVE_ENOUGH
for_suspended_start: false
pipeline_buffering_state: BUFFERING_HAVE_ENOUGH
duration: 777.72916
```
137          mp4        1920x1080  1080p 3838k , avc1.640028, 30fps, video only
140          m4a        audio only DASH audio  131k , m4a_dash container, mp4a.40.2@128k

When the card goes into mode P0 .
![p0](https://user-images.githubusercontent.com/1809702/62026153-770f7780-b1da-11e9-9bee-46242f86724e.png)

When the card is in normal desktop mode P8 or P5.
![p5](https://user-images.githubusercontent.com/1809702/62026164-8262a300-b1da-11e9-8f49-5bcb389d813e.png)

![p8-p0](https://user-images.githubusercontent.com/1809702/62026469-61e71880-b1db-11e9-8398-88384214b115.png)
P0 is level 3 in the `nvidia-settings` app – I rather use `nvidia-smi`. Also when I pause a video for longer than 30 seconds it goes black and I get this log output:
```
vdpau_video: vaTerminate(): output ID 0x05000001 is still allocated, destroying
vdpau_video: vaTerminate(): output ID 0x05000002 is still allocated, destroying
vdpau_video: vaTerminate(): output ID 0x05000003 is still allocated, destroying
vdpau_video: vaTerminate(): output ID 0x05000004 is still allocated, destroying
vdpau_video: vaTerminate(): output ID 0x05000005 is still allocated, destroying
vdpau_video: vaTerminate(): output ID 0x05000006 is still allocated, destroying
vdpau_video: vaTerminate(): output ID 0x05000007 is still allocated, destroying
vdpau_video: vaTerminate(): output ID 0x05000008 is still allocated, destroying
vdpau_video: vaTerminate(): surface ID 0x03000003 is still allocated, destroying
vdpau_video: vaTerminate(): surface ID 0x03000004 is still allocated, destroying
vdpau_video: vaTerminate(): surface ID 0x03000006 is still allocated, destroying
vdpau_video: vaTerminate(): surface ID 0x03000007 is still allocated, destroying
vdpau_video: vaTerminate(): mixer ID 0x09000000 is still allocated, destroying
```
until I click play again. So the VDA is working.

**Comment by saiarcot895** [comment] 2019-07-29 06:35
So the GPU is working, but there's visual (video) issues?

**Comment by omen23** [comment] 2019-07-29 06:40
no it was always like this - after 30 seconds of clicking pause the buffer flushes and the screen is black until i click play again ...

**Comment by omen23** [comment] 2019-07-29 07:07
but I wonder what these attributes are – why it does not seem to affect 10 and 20 series Nvidia cards but older chips... maybe some time for code digging – where the profiles get iterated etc. I even remember the for loop .. we already had a problem there once ..  well maybe you can look into it ... I think the driver version does not matter but I am using `430.26`, but I can downgrade to `418.56`. Maybe it has something to do with CUDA and the [the available feature set on the card](https://en.wikipedia.org/wiki/Nvidia_PureVideo#Nvidia_VDPAU_Feature_Sets).

**Comment by JurgenWolf** [comment] 2019-07-29 12:41
> So the GPU is working, but there's visual (video) issues?
Yes, laggy playback since v75.
Was smooth up to v74.

**Comment by JurgenWolf** [comment] 2019-07-29 12:59
In v74 I still have the ability to disable this laggy/buggy MojoVideoDecoder.
Probably, that's why playback was smooth.

**Comment by omen23** [comment] 2019-07-29 17:11
so for me no laggy playback

**Comment by JurgenWolf** [comment] 2019-07-29 17:19
My VDPAU features are the same as they were always before.
Only Chromium build changed.

**Comment by JurgenWolf** [comment] 2019-07-29 19:53
@saiarcot895 

This patched package `vdpau-video (0.7.4-7ubuntu1~ppa1~18.10.1)` is still required by 75-77 builds?
It is installed on my machine...

**Comment by JurgenWolf** [comment] 2019-07-29 20:10
Just published today by another victim:
https://github.com/saiarcot895/chromium-ubuntu-build/issues/54

So 100% laggy and buggy this MojoVideoDecoder.

**Comment by saiarcot895** [comment] 2019-07-29 20:12
Yes, it's required on systems with nVidia GPUs. Otherwise, hardware video decoding with Chromium won't work. 

On July 29, 2019 12:53:38 PM PDT, JurgenWolf <notifications@github.com> wrote:
>@saiarcot895 
>
>This patched package `vdpau-video (0.7.4-7ubuntu1~ppa1~18.10.1)` is
>still required by 75-77 builds?
>It is installed on my machine...
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/saiarcot895/chromium-ubuntu-build/issues/52#issuecomment-516138036

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by saiarcot895** [comment] 2019-08-02 15:48
Closing this issue as a duplicate of #46.

**Closed by saiarcot895** 2019-08-02 15:48 UTC

**Comment by omen23** [comment] 2019-08-02 17:27
@saiarcot895  you mean the package `vdpau-va-driver` - don't you?
@JurgenWolf 
Kind Regards
